name: Vulnerable Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR Title
        run: echo "Pull Request Title:${{ github.event.pull_request.title }}"
