name: Vulnerable Workflow
on:
  pull_request:
    branches:
      - main

jobs:
  run-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Execute PR Title
        run: echo "Running:${{ github.event.pull_request.title }}"
      - name: Dangerous Command
        run: ${{ github.event.pull_request.title }}
