name: Vulnerable Workflow Script injection 2
on:
  pull_request:
    branches:
      - main

jobs:
  run-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Dangerous Command
        run: ${{ github.event.pull_request.title }}
